name: Build Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # or another version compatible with Jekyll

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      working-directory: ./docs  # Set this to where your site source is located
      run: |
        bundle exec jekyll build
